name: Build and Release Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 依存関係をインストール
        run: npm install

      - name: Electron アプリをビルド
        run: npm run build

      - name: ビルドアーティファクトをアップロード
        uses: actions/upload-artifact@v4
        with:
          name: electron-app
          path: dist/

      - name: GitHub Releases へアップロード (タグがある場合)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
